language: c++
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1
      compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - llvm-5.0
      - llvm-5.0-dev
      - lld-5.0
      - liblz4-dev
install:
  - pip2 install --user -r requirements.txt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=clang++-5.0; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      CXX=clang++
      brew update
      brew install lz4
    fi
script: make CXX=$CXX
after_success:
  - mv ctu ctu_$TRAVIS_OS_NAME
deploy:
    - provider: releases
      api_key: $GITHUB_TOKEN
      file:
        - "ctu_$TRAVIS_OS_NAME"
      skip-cleanup: true
      draft: true
      tag_name: $TRAVIS_TAG
      on:
        tags: true
